### ISSUE TITLE
Finish documentation for Documentation/PawPartner Website

### ISSUE THREAD

**Issue by JaredDanielJones** [Some-Apps/ShelterPartner#82]

**Comment by rhjones777** [comment]
Jared, I can do this one as well if you want to assign it to me.

**Comment by rhjones777** [comment]
I just read that you only assign one issue per person at a time, so I'll finish the logo one, and then if this is still available when that one is done, you can assign me this one. I'll have some logos for you to look at tomorrow afternoon.

**Comment by JaredDanielJones** [comment]
Sounds good!

**Comment by rhjones777** [comment]
I'm ready to work on this one if you'd like to assign it to me.

**Comment by JaredDanielJones** [comment]
Looks good. Was just missing .md on the file name. And when you create the pull request, if you write the issue number in the title or description right after a pound sign, it'll automatically link it to that issue.

**Comment by rhjones777** [comment]
Ahhh, I could not figure out why the view wasn’t working again, but it makes sense since I didn’t have .md. That should remind d me of if I forget here on out. Roger that on the Issue Number linking. I actually still have one page left on it to do, but can I just still link it to that same Issue # even though it’s closed. I probably shouldn’t have pushed it til I finished the whole issue.On Aug 3, 2024, at 18:44, Jared Jones ***@***.***> wrote:﻿
Looks good. Was just missing .md on the file name. And when you create the pull request, if you write the issue number in the title or description right after a pound sign, it'll automatically link it to that issue.

**Comment by JaredDanielJones** [comment]
👍🏼
